version: 0.2

env:
  parameter-store:
    CLOUDFRONT_PRIVATE_KEY_STRING: "/CodeBuild/CLOUDFRONT_PRIVATE_KEY_STRING"

phases:
  install:
    commands:
      - npm install -g serverless
      - npm install
  build:
    commands:
      - npm run lint
      - npm run deploy
  post_build:
    commands:
      - touch dummy.zip

artifacts:
  files:
    - dummy.zip
