# serverless.yml

service: avshare

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ${env:AWS_REGION, 'ap-northeast-1'}
  memorySize: 128
  timeout: 60

plugins:
  - serverless-offline

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      MYNAME: ${env:MYNAME}
      MYPASS: ${env:MYPASS}
      MY_FAVORITES_DOMAIN: d2ri4pj87do1tj.cloudfront.net
      OLD_PROGRAMS_DOMAIN: d1fbdzhz2ci06b.cloudfront.net
      CLOUDFRONT_KEY_PAIR_ID: APKAIZXOXRN6HZYYWLNQ
      CLOUDFRONT_PRIVATE_KEY_STRING: ${env:CLOUDFRONT_PRIVATE_KEY_STRING}
      BUCKET_NAME: jp-live-bruin-iwai-audio-video
    role: appRole

resources:
  Resources:
    appRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: lambdaDefault
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow # note that these rights are given in the default policy and are required if you want logs out of your lambda(s)
                  Action:
                    - logs:CreateLogStream
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - !Sub 'log-group:/aws/lambda/${AWS::StackName}-app:*'
                - Effect: Allow # note that these rights are given in the default policy and are required if you want logs out of your lambda(s)
                  Action:
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - !Sub 'log-group:/aws/lambda/${AWS::StackName}-app:*:*'
          - PolicyName: s3access
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: "Allow"
                  Action:
                    - "s3:GetObject"
                  Resource:
                    - arn:aws:s3:::jp-live-bruin-iwai-audio-video/*
