# serverless.yml

service: avshare

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ${env:AWS_REGION, 'ap-northeast-1'}
  memorySize: 128
  timeout: 60

plugins:
  - serverless-offline

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      MYNAME: ${env:MYNAME}
      MYPASS: ${env:MYPASS}
